import type { Metadata } from "next";
import "@suiet/wallet-kit/style.css";
import "./globals.css";
import { NeedHelp } from "@/components/need-help";
import { Toaster } from "@/components/ui/sonner";
import { WalletProvider } from "@suiet/wallet-kit";
import { ClientProvider } from "@/components/client-provider";

export const metadata: Metadata = {
  title: "PAYFRICA LITE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased overflow-y-auto min-h-screen relative`}>
        <ClientProvider>
          {children}
          {modal}
          <Toaster position="bottom-right" />
          <NeedHelp className="fixed bottom-5 mb-3 right-4 mr-5 z-50 hidden md:flex" />
        </ClientProvider>
      </body>
    </html>
  );
}
